- name: Using the IBM Spectrum Virtualize collection to create an FC host
  hosts: all
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  tasks:
    - name: Define a new FC host
      ibm_svc_host:
        clustername: "{{clustername}}"
        domain: "{{domain}}"
        username: "{{username}}"
        password: "{{password}}"
        log_path: /tmp/fchost-create.debug
        name: "{{fchost}}"
        state: present
        fcwwpn: "{{fcwwpn}}"
        iogrp: 0:1:2:3
        protocol: scsi
        type: generic


