- name: IBM Storage start a Flash Copy Mapping
  hosts: all
  collections:
    - ibm.spectrum_virtualize
#  gather_facts: no
  connection: local
  tasks:
    - name: start a Flash Copy Mapping
      ibm_svc_volume_clone:
        clustername: "{{clustername}}"
        domain: 
        username: "{{username}}"
        password: "{{password}}"
        log_path: /tmp/start-fcmap.debug
        state: start
        name: "{{flashcopymapping}}"
        volume: "{{sourcevol}}"
        clone: "{{targetvol}}"
        restore: true


