- name: IBM Storage stop a Flash Copy Mapping
  hosts: all
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  tasks:
    - name: stop a Flash Copy Mapping
      ibm_svc_volume_clone:
        clustername: "{{clustername}}"
        domain: "{{domain}}"
        username: "{{username}}"
        password: "{{password}}"
        log_path: /tmp/stop-fcmap.debug
        state: stop
        name: "{{flashcopymapping}}"
        volume: "{{sourcevol}}"
        clone: "{{targetvol}}"
        force: true


