- name: Using the IBM Spectrum Virtualize collection
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  connection: local
  hosts: all
  tasks:
    - name: Gather info from storage
      ibm_svc_info:
        clustername: 172.16.15.29
        domain:
        username: superuser
        password: 1qaz@WSX
        log_path: /tmp/playbook.debug
        name: gather_info
        state: info
        gather_subset: all
