- name: Using the IBM Spectrum Virtualize collection to gather storage information
  hosts: all
  collections:
    - ibm.spectrum_virtualize
  gather_facts: no
  tasks:
    - name: Get volume info
      ibm_svc_info:
        clustername: 172.16.13.29
        username: superuser
        password: 1qaz@WSX
        log_path: /tmp/ansible.log
        state: info
        gather_subset: vol
